// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.2
//   protoc               unknown
// source: foo_messages.proto

/* eslint-disable */
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "foo";

export interface User {
  id: number;
  name: string;
}

export interface Foo {
  id: number;
  name: string;
  isPending: boolean;
  createdAt?: Timestamp | undefined;
  user?: User | undefined;
}

export interface PostFooDTO {
  name: string;
}

export interface GetFooDTO {
  id: number;
}

export interface Time {
  time: number;
}

export const FOO_PACKAGE_NAME = "foo";
